services:
  ui:
    build: .
    expose:
      - 8502
    volumes:
      - ./src/:/app/src/
      - /app/.venv
    command: streamlit run src/app.py --server.port 8080
    networks:
      - web

  nginx:
    build: ./nginx
    expose:
      - 80
    depends_on:
      - ui
    environment:
      - VIRTUAL_HOST=barrelytix.charlieavery.site
      - LETSENCRYPT_HOST=barrelytix.charlieavery.site
    networks:
      - web

networks:
  web:
    external: true